/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as GraciasRouteImport } from './routes/gracias'
import { Route as CuentaRouteImport } from './routes/cuenta'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as CarritoRouteImport } from './routes/carrito'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EventoCaifanesReunionRouteImport } from './routes/evento.caifanes-reunion'
import { Route as CuentaWhatsappRouteImport } from './routes/cuenta.whatsapp'
import { Route as CuentaRedesRouteImport } from './routes/cuenta.redes'
import { Route as CuentaPasadosRouteImport } from './routes/cuenta.pasados'
import { Route as CuentaPagosRouteImport } from './routes/cuenta.pagos'
import { Route as CuentaNotificacionesRouteImport } from './routes/cuenta.notificaciones'
import { Route as CuentaIdiomaRouteImport } from './routes/cuenta.idioma'
import { Route as CuentaHistorialRouteImport } from './routes/cuenta.historial'
import { Route as CuentaFavoritosRouteImport } from './routes/cuenta.favoritos'
import { Route as CuentaFacturacionRouteImport } from './routes/cuenta.facturacion'
import { Route as CuentaDatosRouteImport } from './routes/cuenta.datos'
import { Route as CuentaCreditosRouteImport } from './routes/cuenta.creditos'
import { Route as CuentaBoletosRouteImport } from './routes/cuenta.boletos'

const GraciasRoute = GraciasRouteImport.update({
  id: '/gracias',
  path: '/gracias',
  getParentRoute: () => rootRouteImport,
} as any)
const CuentaRoute = CuentaRouteImport.update({
  id: '/cuenta',
  path: '/cuenta',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const CarritoRoute = CarritoRouteImport.update({
  id: '/carrito',
  path: '/carrito',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EventoCaifanesReunionRoute = EventoCaifanesReunionRouteImport.update({
  id: '/evento/caifanes-reunion',
  path: '/evento/caifanes-reunion',
  getParentRoute: () => rootRouteImport,
} as any)
const CuentaWhatsappRoute = CuentaWhatsappRouteImport.update({
  id: '/whatsapp',
  path: '/whatsapp',
  getParentRoute: () => CuentaRoute,
} as any)
const CuentaRedesRoute = CuentaRedesRouteImport.update({
  id: '/redes',
  path: '/redes',
  getParentRoute: () => CuentaRoute,
} as any)
const CuentaPasadosRoute = CuentaPasadosRouteImport.update({
  id: '/pasados',
  path: '/pasados',
  getParentRoute: () => CuentaRoute,
} as any)
const CuentaPagosRoute = CuentaPagosRouteImport.update({
  id: '/pagos',
  path: '/pagos',
  getParentRoute: () => CuentaRoute,
} as any)
const CuentaNotificacionesRoute = CuentaNotificacionesRouteImport.update({
  id: '/notificaciones',
  path: '/notificaciones',
  getParentRoute: () => CuentaRoute,
} as any)
const CuentaIdiomaRoute = CuentaIdiomaRouteImport.update({
  id: '/idioma',
  path: '/idioma',
  getParentRoute: () => CuentaRoute,
} as any)
const CuentaHistorialRoute = CuentaHistorialRouteImport.update({
  id: '/historial',
  path: '/historial',
  getParentRoute: () => CuentaRoute,
} as any)
const CuentaFavoritosRoute = CuentaFavoritosRouteImport.update({
  id: '/favoritos',
  path: '/favoritos',
  getParentRoute: () => CuentaRoute,
} as any)
const CuentaFacturacionRoute = CuentaFacturacionRouteImport.update({
  id: '/facturacion',
  path: '/facturacion',
  getParentRoute: () => CuentaRoute,
} as any)
const CuentaDatosRoute = CuentaDatosRouteImport.update({
  id: '/datos',
  path: '/datos',
  getParentRoute: () => CuentaRoute,
} as any)
const CuentaCreditosRoute = CuentaCreditosRouteImport.update({
  id: '/creditos',
  path: '/creditos',
  getParentRoute: () => CuentaRoute,
} as any)
const CuentaBoletosRoute = CuentaBoletosRouteImport.update({
  id: '/boletos',
  path: '/boletos',
  getParentRoute: () => CuentaRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/carrito': typeof CarritoRoute
  '/checkout': typeof CheckoutRoute
  '/cuenta': typeof CuentaRouteWithChildren
  '/gracias': typeof GraciasRoute
  '/cuenta/boletos': typeof CuentaBoletosRoute
  '/cuenta/creditos': typeof CuentaCreditosRoute
  '/cuenta/datos': typeof CuentaDatosRoute
  '/cuenta/facturacion': typeof CuentaFacturacionRoute
  '/cuenta/favoritos': typeof CuentaFavoritosRoute
  '/cuenta/historial': typeof CuentaHistorialRoute
  '/cuenta/idioma': typeof CuentaIdiomaRoute
  '/cuenta/notificaciones': typeof CuentaNotificacionesRoute
  '/cuenta/pagos': typeof CuentaPagosRoute
  '/cuenta/pasados': typeof CuentaPasadosRoute
  '/cuenta/redes': typeof CuentaRedesRoute
  '/cuenta/whatsapp': typeof CuentaWhatsappRoute
  '/evento/caifanes-reunion': typeof EventoCaifanesReunionRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/carrito': typeof CarritoRoute
  '/checkout': typeof CheckoutRoute
  '/cuenta': typeof CuentaRouteWithChildren
  '/gracias': typeof GraciasRoute
  '/cuenta/boletos': typeof CuentaBoletosRoute
  '/cuenta/creditos': typeof CuentaCreditosRoute
  '/cuenta/datos': typeof CuentaDatosRoute
  '/cuenta/facturacion': typeof CuentaFacturacionRoute
  '/cuenta/favoritos': typeof CuentaFavoritosRoute
  '/cuenta/historial': typeof CuentaHistorialRoute
  '/cuenta/idioma': typeof CuentaIdiomaRoute
  '/cuenta/notificaciones': typeof CuentaNotificacionesRoute
  '/cuenta/pagos': typeof CuentaPagosRoute
  '/cuenta/pasados': typeof CuentaPasadosRoute
  '/cuenta/redes': typeof CuentaRedesRoute
  '/cuenta/whatsapp': typeof CuentaWhatsappRoute
  '/evento/caifanes-reunion': typeof EventoCaifanesReunionRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/carrito': typeof CarritoRoute
  '/checkout': typeof CheckoutRoute
  '/cuenta': typeof CuentaRouteWithChildren
  '/gracias': typeof GraciasRoute
  '/cuenta/boletos': typeof CuentaBoletosRoute
  '/cuenta/creditos': typeof CuentaCreditosRoute
  '/cuenta/datos': typeof CuentaDatosRoute
  '/cuenta/facturacion': typeof CuentaFacturacionRoute
  '/cuenta/favoritos': typeof CuentaFavoritosRoute
  '/cuenta/historial': typeof CuentaHistorialRoute
  '/cuenta/idioma': typeof CuentaIdiomaRoute
  '/cuenta/notificaciones': typeof CuentaNotificacionesRoute
  '/cuenta/pagos': typeof CuentaPagosRoute
  '/cuenta/pasados': typeof CuentaPasadosRoute
  '/cuenta/redes': typeof CuentaRedesRoute
  '/cuenta/whatsapp': typeof CuentaWhatsappRoute
  '/evento/caifanes-reunion': typeof EventoCaifanesReunionRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/carrito'
    | '/checkout'
    | '/cuenta'
    | '/gracias'
    | '/cuenta/boletos'
    | '/cuenta/creditos'
    | '/cuenta/datos'
    | '/cuenta/facturacion'
    | '/cuenta/favoritos'
    | '/cuenta/historial'
    | '/cuenta/idioma'
    | '/cuenta/notificaciones'
    | '/cuenta/pagos'
    | '/cuenta/pasados'
    | '/cuenta/redes'
    | '/cuenta/whatsapp'
    | '/evento/caifanes-reunion'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/carrito'
    | '/checkout'
    | '/cuenta'
    | '/gracias'
    | '/cuenta/boletos'
    | '/cuenta/creditos'
    | '/cuenta/datos'
    | '/cuenta/facturacion'
    | '/cuenta/favoritos'
    | '/cuenta/historial'
    | '/cuenta/idioma'
    | '/cuenta/notificaciones'
    | '/cuenta/pagos'
    | '/cuenta/pasados'
    | '/cuenta/redes'
    | '/cuenta/whatsapp'
    | '/evento/caifanes-reunion'
  id:
    | '__root__'
    | '/'
    | '/carrito'
    | '/checkout'
    | '/cuenta'
    | '/gracias'
    | '/cuenta/boletos'
    | '/cuenta/creditos'
    | '/cuenta/datos'
    | '/cuenta/facturacion'
    | '/cuenta/favoritos'
    | '/cuenta/historial'
    | '/cuenta/idioma'
    | '/cuenta/notificaciones'
    | '/cuenta/pagos'
    | '/cuenta/pasados'
    | '/cuenta/redes'
    | '/cuenta/whatsapp'
    | '/evento/caifanes-reunion'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CarritoRoute: typeof CarritoRoute
  CheckoutRoute: typeof CheckoutRoute
  CuentaRoute: typeof CuentaRouteWithChildren
  GraciasRoute: typeof GraciasRoute
  EventoCaifanesReunionRoute: typeof EventoCaifanesReunionRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/gracias': {
      id: '/gracias'
      path: '/gracias'
      fullPath: '/gracias'
      preLoaderRoute: typeof GraciasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cuenta': {
      id: '/cuenta'
      path: '/cuenta'
      fullPath: '/cuenta'
      preLoaderRoute: typeof CuentaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/carrito': {
      id: '/carrito'
      path: '/carrito'
      fullPath: '/carrito'
      preLoaderRoute: typeof CarritoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/evento/caifanes-reunion': {
      id: '/evento/caifanes-reunion'
      path: '/evento/caifanes-reunion'
      fullPath: '/evento/caifanes-reunion'
      preLoaderRoute: typeof EventoCaifanesReunionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cuenta/whatsapp': {
      id: '/cuenta/whatsapp'
      path: '/whatsapp'
      fullPath: '/cuenta/whatsapp'
      preLoaderRoute: typeof CuentaWhatsappRouteImport
      parentRoute: typeof CuentaRoute
    }
    '/cuenta/redes': {
      id: '/cuenta/redes'
      path: '/redes'
      fullPath: '/cuenta/redes'
      preLoaderRoute: typeof CuentaRedesRouteImport
      parentRoute: typeof CuentaRoute
    }
    '/cuenta/pasados': {
      id: '/cuenta/pasados'
      path: '/pasados'
      fullPath: '/cuenta/pasados'
      preLoaderRoute: typeof CuentaPasadosRouteImport
      parentRoute: typeof CuentaRoute
    }
    '/cuenta/pagos': {
      id: '/cuenta/pagos'
      path: '/pagos'
      fullPath: '/cuenta/pagos'
      preLoaderRoute: typeof CuentaPagosRouteImport
      parentRoute: typeof CuentaRoute
    }
    '/cuenta/notificaciones': {
      id: '/cuenta/notificaciones'
      path: '/notificaciones'
      fullPath: '/cuenta/notificaciones'
      preLoaderRoute: typeof CuentaNotificacionesRouteImport
      parentRoute: typeof CuentaRoute
    }
    '/cuenta/idioma': {
      id: '/cuenta/idioma'
      path: '/idioma'
      fullPath: '/cuenta/idioma'
      preLoaderRoute: typeof CuentaIdiomaRouteImport
      parentRoute: typeof CuentaRoute
    }
    '/cuenta/historial': {
      id: '/cuenta/historial'
      path: '/historial'
      fullPath: '/cuenta/historial'
      preLoaderRoute: typeof CuentaHistorialRouteImport
      parentRoute: typeof CuentaRoute
    }
    '/cuenta/favoritos': {
      id: '/cuenta/favoritos'
      path: '/favoritos'
      fullPath: '/cuenta/favoritos'
      preLoaderRoute: typeof CuentaFavoritosRouteImport
      parentRoute: typeof CuentaRoute
    }
    '/cuenta/facturacion': {
      id: '/cuenta/facturacion'
      path: '/facturacion'
      fullPath: '/cuenta/facturacion'
      preLoaderRoute: typeof CuentaFacturacionRouteImport
      parentRoute: typeof CuentaRoute
    }
    '/cuenta/datos': {
      id: '/cuenta/datos'
      path: '/datos'
      fullPath: '/cuenta/datos'
      preLoaderRoute: typeof CuentaDatosRouteImport
      parentRoute: typeof CuentaRoute
    }
    '/cuenta/creditos': {
      id: '/cuenta/creditos'
      path: '/creditos'
      fullPath: '/cuenta/creditos'
      preLoaderRoute: typeof CuentaCreditosRouteImport
      parentRoute: typeof CuentaRoute
    }
    '/cuenta/boletos': {
      id: '/cuenta/boletos'
      path: '/boletos'
      fullPath: '/cuenta/boletos'
      preLoaderRoute: typeof CuentaBoletosRouteImport
      parentRoute: typeof CuentaRoute
    }
  }
}

interface CuentaRouteChildren {
  CuentaBoletosRoute: typeof CuentaBoletosRoute
  CuentaCreditosRoute: typeof CuentaCreditosRoute
  CuentaDatosRoute: typeof CuentaDatosRoute
  CuentaFacturacionRoute: typeof CuentaFacturacionRoute
  CuentaFavoritosRoute: typeof CuentaFavoritosRoute
  CuentaHistorialRoute: typeof CuentaHistorialRoute
  CuentaIdiomaRoute: typeof CuentaIdiomaRoute
  CuentaNotificacionesRoute: typeof CuentaNotificacionesRoute
  CuentaPagosRoute: typeof CuentaPagosRoute
  CuentaPasadosRoute: typeof CuentaPasadosRoute
  CuentaRedesRoute: typeof CuentaRedesRoute
  CuentaWhatsappRoute: typeof CuentaWhatsappRoute
}

const CuentaRouteChildren: CuentaRouteChildren = {
  CuentaBoletosRoute: CuentaBoletosRoute,
  CuentaCreditosRoute: CuentaCreditosRoute,
  CuentaDatosRoute: CuentaDatosRoute,
  CuentaFacturacionRoute: CuentaFacturacionRoute,
  CuentaFavoritosRoute: CuentaFavoritosRoute,
  CuentaHistorialRoute: CuentaHistorialRoute,
  CuentaIdiomaRoute: CuentaIdiomaRoute,
  CuentaNotificacionesRoute: CuentaNotificacionesRoute,
  CuentaPagosRoute: CuentaPagosRoute,
  CuentaPasadosRoute: CuentaPasadosRoute,
  CuentaRedesRoute: CuentaRedesRoute,
  CuentaWhatsappRoute: CuentaWhatsappRoute,
}

const CuentaRouteWithChildren =
  CuentaRoute._addFileChildren(CuentaRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CarritoRoute: CarritoRoute,
  CheckoutRoute: CheckoutRoute,
  CuentaRoute: CuentaRouteWithChildren,
  GraciasRoute: GraciasRoute,
  EventoCaifanesReunionRoute: EventoCaifanesReunionRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
